#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP -d 1 2 3 4 5 6

bspc config focused_border_color "#8C7868"
bspc config normal_border_color "#2B2B2B"
bspc config active_border_color "#cc241d"

bspc config border_width         4
bspc config window_gap           10
bspc config pointer_modifier mod4

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

dunst
nm-applet # Internet selector
xset r rate 300 50 # making keys feel smoother
xrandr --output eDP --set TearFree on # Turning "VSYNC" on
picom -b # Compositor
$HOME/.screenlayout/dualmonitors.sh # Setting screens up
nitrogen --restore # Wallpaper setter
$HOME/.config/polybar/launch.sh # Bar
